# /spaceships

### GET request | get all spaceships
GET http://localhost:3000/spaceships/ HTTP/1.1

### POST request | post request with valid body
POST http://localhost:3000/spaceships HTTP/1.1
Content-Type: application/json

{
    "model": "BBBB",
    "manufacturer": "Deivid",
    "capacity": 10
}

### POST request | post spaceship that already exists
POST http://localhost:3000/spaceships HTTP/1.1
Content-Type: application/json

{
    "model": "BBBB",
    "manufacturer": "Deivid",
    "capacity": 10
}

### POST request | post request with invalid body
POST http://localhost:3000/spaceships HTTP/1.1
Content-Type: application/json

{
    "model": "BBBB",
    "capacity": 10
}

### GET request | get a spaceship
GET http://localhost:3000/spaceships/1 HTTP/1.1

### GET request | get spaceship that doesn't exists
GET http://localhost:3000/spaceships/99 HTTP/1.1

### PUT request | update entity
PUT http://localhost:3000/spaceships/1 HTTP/1.1
Content-Type: application/json

{
    "manufacturer": "Deividollar"
}

### PUT request | update non existent entity
PUT http://localhost:3000/spaceships/99 HTTP/1.1
Content-Type: application/json

{
    "manufacturer": "Deividollar"
}

### DELETE request | delete a entity
DELETE http://localhost:3000/spaceships/20 HTTP/1.1


### DELETE request | delete request on entity that doesn't exists
DELETE http://localhost:3000/spaceships/2 HTTP/1.1

# -----------------------------------------------------------------



# /stellar-systems

### GET
GET http://localhost:3000/stellar-systems/ HTTP/1.1

### GET 

GET http://localhost:3000/stellar-systems/2 HTTP/1.1

### POST
POST http://localhost:3000/stellar-systems/ HTTP/1.1
Content-Type: application/json

{
    "name": "Nova Nação",
    "description": "Ar de morto, morto no chão."
}

### PUT
PUT http://localhost:3000/stellar-systems/1 HTTP/1.1
Content-Type: application/json

{
    "name": "Deividollar"
}

### DELETE
DELETE http://localhost:3000/stellar-systems/9 HTTP/1.1

# -----------------------------------------------------------------



# /register

### POST | post valid user
POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
    "username": "Deivid",
    "email": "deivid6@gmail.com",
    "password": "1234"
}


### POST | post invalid user
POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
    "name": "Nova Nação",
    "description": "Ar de morto, morto no chão."
}


### POST | post same user
POST http://localhost:3000/ HTTP/1.1
Content-Type: application/json

{
    "username": "Deivid",
    "email": "deivid@gmail.com",
    "password": "1234"
}
